name: Docker Build (AMD64 Only) - Fast

# This workflow runs on pushes to main branch and PRs for fast development builds
on:
  push:
    tags:
      - 'v*.*.*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  build-and-push-amd64:
    # The type of runner that the job will run on.
    runs-on: ubuntu-latest

    # Grant GITHUB_TOKEN permissions to write to GitHub Packages (GHCR).
    permissions:
      contents: read
      packages: write

    steps:
      # 1. Checkout the repository code.
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Docker Buildx, the advanced builder.
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Extract metadata (tags, labels) for Docker.
      # This action automatically creates useful tags for your image based on the Git context.
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=raw,value=dev,enable={{is_default_branch}}
          labels: |
            org.opencontainers.image.title=nextcloud-public-uploader
            org.opencontainers.image.description=Nextcloud Public Uploader (Development)
            org.opencontainers.image.vendor=${{ github.repository_owner }}

      # 4. Log in to the container registry.
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 5. Build and push the Docker image (AMD64 only for speed).
      - name: Build and push Docker image (AMD64)
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # Pass version information as build arguments
          build-args: |
            VERSION=${{ github.ref_name }}
            COMMIT=${{ github.sha }}
            DATE=${{ github.event.head_commit.timestamp }}
          # Enable build caching to speed up future builds
          cache-from: type=gha
          cache-to: type=gha,mode=max
